package PokemonInit;

import static org.junit.Assert.*;

import org.junit.Test;

public class testPokemon {

	@Test
	public void testBulbasaur() {
		Pokemon bul = new Bulbasaur();
		assertEquals("Bulbasaur",bul.getName());
		assertEquals("normal",bul.getRarity());
		assertEquals("grass",bul.getProperty());
		assertEquals(45,bul.getHP());
		assertEquals(45,bul.getMP());
		assertEquals(45,bul.getMaxHP());
		assertEquals(45,bul.getMaxMP());
		assertEquals(10,bul.getExp());
		assertEquals(10,bul.getMoney());
		assertEquals(1,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(40,bul.getHP());
		assertEquals(40,bul.getMP());
		assertEquals(40,bul.getMaxHP());
		assertEquals(40,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(45,bul.getHP());
		assertEquals(45,bul.getMP());
		assertEquals(45,bul.getMaxHP());
		assertEquals(45,bul.getMaxMP());
		assertEquals(10,bul.trueAttack("fighting"));
		assertEquals(5,bul.trueAttack("fire"));
		assertEquals(20,bul.trueAttack("electric"));
		bul.lvlup(100);
		assertEquals(2,bul.getLevel());
		assertEquals(50,bul.getHP());
		assertEquals(50,bul.getMP());
		assertEquals(50,bul.getMaxHP());
		assertEquals(50,bul.getMaxMP());
		assertEquals(12,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testButterfree() {
		Pokemon but = new Butterfree();
		assertEquals("Butterfree",but.getName());
		assertEquals("rare",but.getRarity());
		assertEquals("Bug",but.getProperty());
		assertEquals(60,but.getHP());
		assertEquals(60,but.getMP());
		assertEquals(60,but.getMaxHP());
		assertEquals(60,but.getMaxMP());
		assertEquals(100,but.getExp());
		assertEquals(100,but.getMoney());
		assertEquals(16,but.getLevel());
		assertEquals(true,but.ifwild());
		but.changeHP(5);
		but.changeMP(5);
		but.changeMaxHP(5);
		but.changeMaxMP(5);
		assertEquals(55,but.getHP());
		assertEquals(55,but.getMP());
		assertEquals(55,but.getMaxHP());
		assertEquals(55,but.getMaxMP());
		but.changeHP(-5);
		but.changeMP(-5);
		but.changeMaxHP(-5);
		but.changeMaxMP(-5);
		assertEquals(60,but.getHP());
		assertEquals(60,but.getMP());
		assertEquals(60,but.getMaxHP());
		assertEquals(60,but.getMaxMP());
		assertEquals(20,but.trueAttack("Bug"));
		assertEquals(25,but.trueAttack("electric"));
		but.lvlup(200);
		assertEquals(18,but.getLevel());
		assertEquals(70,but.getHP());
		assertEquals(70,but.getMP());
		assertEquals(70,but.getMaxHP());
		assertEquals(70,but.getMaxMP());
		
	}
	
	@Test
	public void testCharizard() {
		Pokemon bul = new Charizard();
		assertEquals("Charizard",bul.getName());
		assertEquals("rare",bul.getRarity());
		assertEquals("fire",bul.getProperty());
		assertEquals(78,bul.getHP());
		assertEquals(60,bul.getMP());
		assertEquals(78,bul.getMaxHP());
		assertEquals(60,bul.getMaxMP());
		assertEquals(100,bul.getExp());
		assertEquals(100,bul.getMoney());
		assertEquals(16,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(73,bul.getHP());
		assertEquals(55,bul.getMP());
		assertEquals(73,bul.getMaxHP());
		assertEquals(55,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(78,bul.getHP());
		assertEquals(60,bul.getMP());
		assertEquals(78,bul.getMaxHP());
		assertEquals(60,bul.getMaxMP());
		assertEquals(50,bul.trueAttack("grass"));
		assertEquals(12,bul.trueAttack("water"));
		assertEquals(25,bul.trueAttack("electric"));
		bul.lvlup(100);
		assertEquals(17,bul.getLevel());
		assertEquals(83,bul.getHP());
		assertEquals(65,bul.getMP());
		assertEquals(83,bul.getMaxHP());
		assertEquals(65,bul.getMaxMP());
		assertEquals(27,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testCharmander() {
		Pokemon bul = new Charmander();
		assertEquals("Charmander",bul.getName());
		assertEquals("normal",bul.getRarity());
		assertEquals("fire",bul.getProperty());
		assertEquals(39,bul.getHP());
		assertEquals(50,bul.getMP());
		assertEquals(39,bul.getMaxHP());
		assertEquals(50,bul.getMaxMP());
		assertEquals(10,bul.getExp());
		assertEquals(10,bul.getMoney());
		assertEquals(1,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(34,bul.getHP());
		assertEquals(45,bul.getMP());
		assertEquals(34,bul.getMaxHP());
		assertEquals(45,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(39,bul.getHP());
		assertEquals(50,bul.getMP());
		assertEquals(39,bul.getMaxHP());
		assertEquals(50,bul.getMaxMP());
		assertEquals(30,bul.trueAttack("grass"));
		assertEquals(15,bul.trueAttack("fire"));
		assertEquals(7,bul.trueAttack("water"));
		bul.lvlup(100);
		assertEquals(2,bul.getLevel());
		assertEquals(44,bul.getHP());
		assertEquals(55,bul.getMP());
		assertEquals(44,bul.getMaxHP());
		assertEquals(55,bul.getMaxMP());
		assertEquals(17,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testJigglypuff() {
		Pokemon bul = new Jigglypuff();
		assertEquals("Jigglypuff",bul.getName());
		assertEquals("rare",bul.getRarity());
		assertEquals("Fairy",bul.getProperty());
		assertEquals(115,bul.getHP());
		assertEquals(45,bul.getMP());
		assertEquals(115,bul.getMaxHP());
		assertEquals(45,bul.getMaxMP());
		assertEquals(30,bul.getExp());
		assertEquals(30,bul.getMoney());
		assertEquals(1,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(110,bul.getHP());
		assertEquals(40,bul.getMP());
		assertEquals(110,bul.getMaxHP());
		assertEquals(40,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(115,bul.getHP());
		assertEquals(45,bul.getMP());
		assertEquals(115,bul.getMaxHP());
		assertEquals(45,bul.getMaxMP());
		assertEquals(5,bul.trueAttack("fighting"));
		assertEquals(5,bul.trueAttack("fire"));
		assertEquals(5,bul.trueAttack("electric"));
		bul.lvlup(100);
		assertEquals(2,bul.getLevel());
		assertEquals(120,bul.getHP());
		assertEquals(50,bul.getMP());
		assertEquals(120,bul.getMaxHP());
		assertEquals(50,bul.getMaxMP());
		assertEquals(7,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testManKey() {
		Pokemon bul = new ManKey();
		assertEquals("ManKey",bul.getName());
		assertEquals("normal",bul.getRarity());
		assertEquals("fighting",bul.getProperty());
		assertEquals(40,bul.getHP());
		assertEquals(40,bul.getMP());
		assertEquals(40,bul.getMaxHP());
		assertEquals(40,bul.getMaxMP());
		assertEquals(10,bul.getExp());
		assertEquals(10,bul.getMoney());
		assertEquals(1,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(35,bul.getHP());
		assertEquals(35,bul.getMP());
		assertEquals(35,bul.getMaxHP());
		assertEquals(35,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(40,bul.getHP());
		assertEquals(40,bul.getMP());
		assertEquals(40,bul.getMaxHP());
		assertEquals(40,bul.getMaxMP());
		assertEquals(15,bul.trueAttack("fighting"));
		assertEquals(0,bul.trueAttack("pisonic"));
//		assertEquals(20,bul.trueAttack("electric"));
		bul.lvlup(100);
		assertEquals(2,bul.getLevel());
		assertEquals(45,bul.getHP());
		assertEquals(45,bul.getMP());
		assertEquals(45,bul.getMaxHP());
		assertEquals(45,bul.getMaxMP());
		assertEquals(17,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testMew() {
		Pokemon bul = new Mew();
		assertEquals("Mew",bul.getName());
		assertEquals("extremely rare",bul.getRarity());
		assertEquals("pisonic",bul.getProperty());
		assertEquals(200,bul.getHP());
		assertEquals(200,bul.getMP());
		assertEquals(200,bul.getMaxHP());
		assertEquals(200,bul.getMaxMP());
		assertEquals(1000,bul.getExp());
		assertEquals(1000,bul.getMoney());
		assertEquals(50,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(195,bul.getHP());
		assertEquals(195,bul.getMP());
		assertEquals(195,bul.getMaxHP());
		assertEquals(195,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(200,bul.getHP());
		assertEquals(200,bul.getMP());
		assertEquals(200,bul.getMaxHP());
		assertEquals(200,bul.getMaxMP());
		assertEquals(70,bul.trueAttack("fighting"));
		assertEquals(70,bul.trueAttack("fire"));
		assertEquals(70,bul.trueAttack("electric"));
		bul.lvlup(100);
		assertEquals(51,bul.getLevel());
		assertEquals(205,bul.getHP());
		assertEquals(205,bul.getMP());
		assertEquals(205,bul.getMaxHP());
		assertEquals(205,bul.getMaxMP());
		assertEquals(72,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testNinetales() {
		Pokemon bul = new Ninetales();
		assertEquals("Ninetales",bul.getName());
		assertEquals("rare",bul.getRarity());
		assertEquals("fire",bul.getProperty());
		assertEquals(73,bul.getHP());
		assertEquals(70,bul.getMP());
		assertEquals(73,bul.getMaxHP());
		assertEquals(70,bul.getMaxMP());
		assertEquals(100,bul.getExp());
		assertEquals(100,bul.getMoney());
		assertEquals(16,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(68,bul.getHP());
		assertEquals(65,bul.getMP());
		assertEquals(68,bul.getMaxHP());
		assertEquals(65,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(73,bul.getHP());
		assertEquals(70,bul.getMP());
		assertEquals(73,bul.getMaxHP());
		assertEquals(70,bul.getMaxMP());
		assertEquals(50,bul.trueAttack("grass"));
		assertEquals(25,bul.trueAttack("fire"));
		assertEquals(12,bul.trueAttack("water"));
		bul.lvlup(100);
		assertEquals(17,bul.getLevel());
		assertEquals(78,bul.getHP());
		assertEquals(75,bul.getMP());
		assertEquals(78,bul.getMaxHP());
		assertEquals(75,bul.getMaxMP());
		assertEquals(27,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testPikachu() {
		Pokemon bul = new Pikachu();
		assertEquals("Pikachu",bul.getName());
		assertEquals("normal",bul.getRarity());
		assertEquals("electric",bul.getProperty());
		assertEquals(35,bul.getHP());
		assertEquals(60,bul.getMP());
		assertEquals(35,bul.getMaxHP());
		assertEquals(60,bul.getMaxMP());
		assertEquals(10,bul.getExp());
		assertEquals(10,bul.getMoney());
		assertEquals(1,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(30,bul.getHP());
		assertEquals(55,bul.getMP());
		assertEquals(30,bul.getMaxHP());
		assertEquals(55,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(35,bul.getHP());
		assertEquals(60,bul.getMP());
		assertEquals(35,bul.getMaxHP());
		assertEquals(60,bul.getMaxMP());
		assertEquals(6,bul.trueAttack("grass"));
		assertEquals(26,bul.trueAttack("water"));
		assertEquals(13,bul.trueAttack("electric"));
		bul.lvlup(100);
		assertEquals(2,bul.getLevel());
		assertEquals(40,bul.getHP());
		assertEquals(65,bul.getMP());
		assertEquals(40,bul.getMaxHP());
		assertEquals(65,bul.getMaxMP());
		assertEquals(15,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testSquirtle() {
		Pokemon bul = new Squirtle();
		assertEquals("Squirtle",bul.getName());
		assertEquals("normal",bul.getRarity());
		assertEquals("water",bul.getProperty());
		assertEquals(44,bul.getHP());
		assertEquals(44,bul.getMP());
		assertEquals(44,bul.getMaxHP());
		assertEquals(44,bul.getMaxMP());
		assertEquals(10,bul.getExp());
		assertEquals(10,bul.getMoney());
		assertEquals(1,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(39,bul.getHP());
		assertEquals(39,bul.getMP());
		assertEquals(39,bul.getMaxHP());
		assertEquals(39,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(44,bul.getHP());
		assertEquals(44,bul.getMP());
		assertEquals(44,bul.getMaxHP());
		assertEquals(44,bul.getMaxMP());
		assertEquals(11,bul.trueAttack("fighting"));
		assertEquals(5,bul.trueAttack("electric"));
		assertEquals(22,bul.trueAttack("fire"));
		bul.lvlup(100);
		assertEquals(2,bul.getLevel());
		assertEquals(49,bul.getHP());
		assertEquals(49,bul.getMP());
		assertEquals(49,bul.getMaxHP());
		assertEquals(49,bul.getMaxMP());
		assertEquals(13,bul.trueAttack("fighting"));
	}
	
	@Test
	public void testVulpix() {
		Pokemon bul = new Vulpix();
		assertEquals("Vulpix",bul.getName());
		assertEquals("normal",bul.getRarity());
		assertEquals("fire",bul.getProperty());
		assertEquals(38,bul.getHP());
		assertEquals(48,bul.getMP());
		assertEquals(38,bul.getMaxHP());
		assertEquals(48,bul.getMaxMP());
		assertEquals(10,bul.getExp());
		assertEquals(10,bul.getMoney());
		assertEquals(1,bul.getLevel());
		assertEquals(true,bul.ifwild());
		bul.changeHP(5);
		bul.changeMP(5);
		bul.changeMaxHP(5);
		bul.changeMaxMP(5);
		assertEquals(33,bul.getHP());
		assertEquals(43,bul.getMP());
		assertEquals(33,bul.getMaxHP());
		assertEquals(43,bul.getMaxMP());
		bul.changeHP(-5);
		bul.changeMP(-5);
		bul.changeMaxHP(-5);
		bul.changeMaxMP(-5);
		assertEquals(38,bul.getHP());
		assertEquals(48,bul.getMP());
		assertEquals(38,bul.getMaxHP());
		assertEquals(48,bul.getMaxMP());
		assertEquals(14,bul.trueAttack("fighting"));
		assertEquals(28,bul.trueAttack("grass"));
		assertEquals(7,bul.trueAttack("water"));
		bul.lvlup(100);
		assertEquals(2,bul.getLevel());
		assertEquals(43,bul.getHP());
		assertEquals(53,bul.getMP());
		assertEquals(43,bul.getMaxHP());
		assertEquals(53,bul.getMaxMP());
		assertEquals(16,bul.trueAttack("fighting"));
	}
}
